spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 63447571172-sou6k458l4450f5902ovjmh563qb26sh.apps.googleusercontent.com
            client-secret: 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